name: ascii_camera
description: ASCII Camera art.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ffi: ^1.1.2
  camera: ^0.9.4+14
  webview_flutter: ^3.0.1
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.0.2

  # state management
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_icons:
  image_path: assets/icon.png
  remove_alpha_ios: true
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/index.html
    - assets/icon.png

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon.png
  android: true
  ios: true
